language: python
python: 3.6

env:
  - TOXENV=py36
  - TOXENV=flake8

install: pip install -U tox

script: tox -e ${TOXENV}

deploy:
  on:
    condition: $TOXENV == py310
    repo: tintoy/seqlog
    tags: true

  provider: pypi
  user: tintoy
  password:
    secure: !!binary |
      Vkc5VUxuc1dDQWxHdkJ3SEpTR2JkcXhaOGNvTklONVRxaG8vOSt0Z2llMENpT3FIVFVPZjZGZDBX
      cnpVUjNmMy9zaTFaU01yRDBYU2pWd3F3TzBOcEhscTRGMWVwN2Q1eUExcWFEK09TNnhzUU1IazFX
      MURvWEN1cU03WXlpR1pLdlFRVnZqR2pMN3NtdXIzKzA1VDd3RUl3Y0c4bVhmR3VyM2xaMGlNOENm
      L0MrUG5GdUNhSmtCOWJDdDk0MG5XY1FOQXlxMFo4L1B1L2dKekZVbmxnbHZ5ODFuVkFKNUhvdzMy
      VjdGNTIrbDBxYmhVQnphRWFRRkQrSXF5LzVSaTB0ekFPVUhWL1lpV1FRc1BFUHlaSzdyZmx6alll
      YjdEOWZXWmgyMTdkMWRUUDk1dkluenJxZTF4NDc3SE8yNlYyUlh2MVZuOXczNGxWNHU2dkx1a2V6
      YTU4cXpra1hSeTNYZEZZMWJlU0hDTlliU2J2cnhSVExSVnZQa2NEM0RMdVdFcjNzbFBWVlRrZ0pT
      T0R5bUZQWjNZejFDdlZDaGpWc1ZqaCtSZTF3UHJEVEI2S0tTcjV5QWJKenRJNjJXU1FMNG5oWXdX
      b3JQbFFmQlg3eW9ZSnIyd3JmZkcxL3FmTndoNyt5NkU0RlJRbmRnY3ZHcVN4MHRkRCtCTWN3bjd3
      cDBjbGtVZXhucVQ3QjllaTkwOTloQ2tHbXd1SUNmbzRUTTlrbklvanI0OEEzR1FEak5LaGM0SWVq
      cEprWnBZMVpCY2Y5akl4WkhWSkdyV1YvTkhMZWt1bko5cVc0b0ErUjVXVlJpK1BYWHJ0cEJKNEFR
      ZWp5MU5DWVZVRU1jV3NWaDlJaCs2aVRKNjgvWU9HVDczSnF3MWpPa3lWbkthZHVoOHNhemVhdDA9

  distributions: sdist bdist_wheel
